<?php
/**
 * 系统配置文件
 */
return [
	'login_captcha' => '1',
	'download_url' => 'https://appdownload.hmbao520.com/',
	'reg_url' => 'https://h5.yunshuch.net/#/pages/login/register',
	'online_service' => '',
	'notice' => '新年新气象，零碳金服祝愿广大会员在新的一年里身体健康，财源滚滚。零碳金服将会陪伴您度过一个又一个新年！',
	'popups_onoff' => '0',
	'popups_content' => '<p style="text-align: center;"></p><p style="text-align: center;"></p><p style="text-align: center;"></p><p style="text-align: center;"></p><p style="text-align: center;"><b>2025年8月22</b><b>日《愿美好如约而至》</b></p><p style="text-align: center;"><b>线上会议10:00-11:00进行</b></p><p style="text-align: center;"><b>入场时间：9:30</b></p><p style="text-align: center;"><img src="/upload/default/20250822/64cdaaf65276382b6da45491354ea2a7.jpg" alt="undefined"><br></p><p style="text-align: center;"><b>连续签到奖励：每月连续签到20次以上，奖励3万待提余额</b></p><p style="text-align: center;"><b>邀请好友奖励：邀请100位好友以上参加会议，奖励50元现金</b></p><p style="text-align: center;"><span style="text-align: start;"><b>重要通知</b></span></p>',
	'file' => '',
	'rate' => '0.1',
	'sign_in_reward' => '666',
	'generation_reward' => '25',
	'second-generation_rewards' => '5',
	'third-generation_rewards' => '0',
	'prize_amount' => '182314263',
	'pension_amount' => '800000',
	'recharge_rate' => '1',
	'recharge_parent_rate' => '',
	'insurance_open' => '0',
	'settlement_open' => '1',
    'apply_bank_open' => '0',
	'receive_open' => '0',
	'withdraw_open' => '0',
	'min_withdraw' => '100',
	'today_withdraw' => '2000000000000',
	'widthdraw_except_holidays' => '1',
	'am_withdraw_start' => '9',
	'am_withdraw_end' => '12',
	'pm_withdraw_start' => '12',
	'pm_withdraw_end' => '16',
	'product_set' => '42',
	'sign_amount' => '3000',
	'app_update_open' => '1',
	'app_update_version' => '3.3.2',
	'app_update_text' => '普惠养老新版本更新',
	'app_update_url' => 'https://aaa.huimb88.cloud/wgt/phyl-3.3.2.wgt',
	'app_ios_download_url' => '',
];